name: streams_channel
description: Extended EventChannel that allow multiple streams with different parameters
version: 0.0.1
author: Loup Inc. <hello@intheloup.io>
homepage: https://github.com/loup-v/streams_channel

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.intheloup.streamschannel
    pluginClass: StreamsChannelPlugin